name: disgord

services:
  app:
    build: .
    image: ghcr.io/birabittoh/disgord:main
    container_name: 'disgord'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
