name: disgord

services:
  app:
    build: .
    image: ghcr.io/birabittoh/disgord:main
    container_name: 'disgord'
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.json:/app/config.json
